[package]
name = "raw-gpu-handle"
description = "GPU API object interoperability crate"
readme = "../readme.md"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true

[dependencies]
